import {
  createContext,
  type ReactNode,
  useContext,
  useMemo,
  useState,
} from "react";
import type { SupportedFoodLabel } from "../api/types";

export type Language = "en" | "zh";

const translations = {
  en: {
    advice: "Advice",
    allergies: "Allergies",
    askAi: "Ask Advisor",
    askAdvice: "Ask Advisor",
    askAdviceCopy: "Get personalized advice from your current fruit.",
    askAdvicePlaceholder: "Ask about today's fruit, meals, or what to buy next.",
    ate: "Ate",
    avoid: "Avoid",
    backToday: "Back to Today",
    bought: "Bought",
    cameraSaw: "Camera saw",
    check: "Check",
    checkingLatestFruitBatches: "Checking the latest fruit batches.",
    close: "Close",
    confirm: "Confirm",
    confirmChange: "Confirm change",
    confirmedQuantity: "Confirmed quantity",
    confirmInventoryChange: "Confirm inventory change",
    confirmInventoryFirst:
      "Confirm changes in Inventory before relying on today's plan.",
    consumed: "Consumed",
    currentConfirmedStock: "Current confirmed stock is",
    dayUnit: "day",
    decreaseQuantity: "Decrease quantity",
    dietPreferences: "Diet Preferences",
    discarded: "Discarded",
    eatSmarter: "Eat smarter",
    eatSoon: "Eat soon",
    everyTwoDays: "Every 2 days",
    eventQuantity: "Event quantity",
    fallbackGuidance:
      "The request was not fully accepted, so the app is showing fallback guidance from available inventory data.",
    fresh: "Fresh",
    fridge: "Fridge",
    freezer: "Freezer",
    healthGoals: "Health Goals",
    home: "Home",
    household: "Household",
    increaseQuantity: "Increase quantity",
    inventory: "Inventory",
    inventoryDetails: "details",
    inventoryIsOffline: "Inventory is offline",
    inventorySummary: "Inventory summary",
    items: "items",
    keepAFewDays: "Keep a few days",
    keepCurrent: "Keep current",
    kitchenStock: "Kitchen stock",
    languageToggle: "中文",
    lightMeals: "Light meals",
    loadingInventory: "Loading inventory",
    lowSugar: "Low Sugar",
    moreCarefulReasoning: "More careful reasoning",
    needCheck: "Need Check",
    needCheckEmpty: "Nothing is marked for checking.",
    newBatch: "New batch",
    newQuantity: "New quantity",
    noRecentScan: "No recent scan",
    noFruitBatches: "No fruit batches",
    noFruitBatchesCopy:
      "Apple, Banana, Litchi, and Pear will appear here after recognition.",
    noFruitCopy: "Add apple, banana, litchi, or pear to see today's plan.",
    noFruitTitle: "No fruit yet",
    noShoppingAdvice: "No shopping advice",
    noShoppingAdviceCopy:
      "Your apple, banana, litchi, and pear inventory does not need a shopping note right now.",
    none: "None",
    nothingUrgent: "Nothing urgent today",
    nothingUrgentCopy:
      "Your available fruit looks calm. Check the list below for anything that needs confirmation.",
    notRecommendedDirect: "Check required",
    pantry: "Pantry",
    optionalSearchContext: "Optional search context",
    pastReferenceDays: "days past reference",
    patchInventory: "Edit",
    pending: "Pending",
    pendingChange: "Pending change",
    pieces: "pieces",
    possibleAdded: "Possibly added",
    possibleUsed: "Possibly used",
    profile: "Profile",
    priority: "Today's priority",
    priorityEmpty: "No fruit is ready to prioritize right now.",
    quickFoodEvents: "Quick food events",
    recommended: "Recommended",
    reminders: "Reminders",
    remindAgainIn: "Remind again in",
    retry: "Retry",
    shoppingAdvice: "Shopping advice",
    shoppingDuplicateSummary: "no need to buy again for now",
    sendAdviceRequest: "Send advice request",
    thinkingAboutAdvice: "Thinking through your advice",
    simplePrep: "Simple prep",
    somethingNeedsAttention: "Something needs attention",
    storageLocation: "Storage location",
    storageUnset: "Storage unset",
    updated: "Updated",
    loading: "Loading",
    pleaseTryAgain: "Please try again in a moment.",
    today: "Today",
    tossed: "Tossed",
    useToday: "use today",
    unknown: "Unknown",
    waitingConfirmation: "waiting for confirmation",
    weightManagement: "Weight Management",
    editProfileSection: "Edit profile section",
    editProfile: "Edit profile",
    expiring: "Expiring",
    profileGoalTitle: "Goal",
    profileGoalHint: "Keep the recommendation direction practical.",
    profileGoalPlaceholder: "Eat fruit before it loses freshness",
    profileDietTitle: "Diet Preference",
    profileDietHint: "Short preference for daily food advice.",
    profileDietPlaceholder: "Light, low sugar, fruit first",
    profileCookingTitle: "Cooking Condition",
    profileCookingHint: "What you can prepare at home.",
    profileCookingPlaceholder: "No oven, simple washing and slicing",
    profileAvoidTitle: "Avoid Foods",
    profileAvoidHint: "Only MVP fruit options are supported.",
    profileAvoidLabel: "Fruit to avoid",
    profileAllergiesTitle: "Allergies",
    profileAllergiesHint: "Optional notes used by food advice.",
    profileHealthNotesTitle: "Health Notes",
    profileHealthNotesHint: "Optional constraints to keep recommendations calm.",
    profileOptionalPlaceholder: "Optional",
    saveProfile: "Save Profile",
    saving: "Saving",
    referenceDateToday: "Reference date today",
    checkTiming: "Check timing",
    daysLeft: "days left",
    daysUnit: "days",
    dayLeft: "day left",
    seen: "Seen",
    total: "Total",
  },
  zh: {
    advice: "建议",
    allergies: "过敏源",
    askAi: "询问建议",
    askAdvice: "询问建议",
    askAdviceCopy: "根据当前水果获得个性化建议。",
    askAdvicePlaceholder: "询问今天吃什么",
    ate: "已食用",
    avoid: "避免",
    backToday: "返回今日",
    bought: "已购买",
    cameraSaw: "镜头识别到",
    check: "检查",
    checkingLatestFruitBatches: "正在检查最新水果库存。",
    close: "关闭",
    confirm: "确认",
    confirmChange: "确认变动",
    confirmedQuantity: "确认数量",
    confirmInventoryChange: "确认库存变动",
    confirmInventoryFirst: "请先在库存中确认变动，再参考今日计划。",
    consumed: "已食用",
    currentConfirmedStock: "当前确认库存为",
    dayUnit: "天",
    decreaseQuantity: "减少数量",
    dietPreferences: "饮食偏好",
    discarded: "已丢弃",
    eatSmarter: "吃得更聪明",
    eatSoon: "尽快食用",
    everyTwoDays: "每 2 天",
    eventQuantity: "本次数量",
    fallbackGuidance: "请求未完全通过，当前显示基于可用库存数据的备用建议。",
    fresh: "新鲜",
    fridge: "冷藏",
    freezer: "冷冻",
    healthGoals: "健康目标",
    home: "首页",
    household: "家庭",
    increaseQuantity: "增加数量",
    inventory: "库存",
    inventoryDetails: "详情",
    inventoryIsOffline: "库存暂不可用",
    inventorySummary: "库存概览",
    items: "项",
    keepAFewDays: "再放几天",
    keepCurrent: "保持当前",
    kitchenStock: "厨房库存",
    languageToggle: "EN",
    lightMeals: "清淡饮食",
    loadingInventory: "正在加载库存",
    lowSugar: "低糖",
    moreCarefulReasoning: "更谨慎地分析",
    needCheck: "需要检查",
    needCheckEmpty: "暂无需要检查的水果。",
    newBatch: "新批次",
    newQuantity: "新识别数量",
    noRecentScan: "暂无近期识别",
    noFruitBatches: "暂无水果批次",
    noFruitBatchesCopy: "识别到苹果、香蕉、荔枝或梨后会显示在这里。",
    noFruitCopy: "添加苹果、香蕉、荔枝或梨后查看今日计划。",
    noFruitTitle: "暂无水果",
    noShoppingAdvice: "暂无采购建议",
    noShoppingAdviceCopy: "当前苹果、香蕉、荔枝和梨库存暂不需要采购提醒。",
    none: "无",
    nothingUrgent: "今日暂无紧急项",
    nothingUrgentCopy: "当前可用水果状态平稳，请查看下方是否有待确认项目。",
    notRecommendedDirect: "需要检查",
    pantry: "常温",
    optionalSearchContext: "可选搜索背景",
    pastReferenceDays: "天超过参考期",
    patchInventory: "更改",
    pending: "待确认",
    pendingChange: "待确认变动",
    pieces: "个",
    possibleAdded: "可能新增",
    possibleUsed: "可能已食用",
    profile: "资料",
    priority: "今日优先吃",
    priorityEmpty: "当前没有需要优先安排的水果。",
    quickFoodEvents: "快速记录",
    recommended: "推荐",
    reminders: "提醒",
    remindAgainIn: "几天后提醒",
    retry: "重试",
    shoppingAdvice: "采购建议",
    shoppingDuplicateSummary: "暂时不用重复购买",
    sendAdviceRequest: "发送建议请求",
    thinkingAboutAdvice: "正在认真分析建议",
    simplePrep: "简单处理",
    somethingNeedsAttention: "有内容需要处理",
    storageLocation: "储存位置",
    storageUnset: "未设置储存位置",
    updated: "更新于",
    loading: "加载中",
    pleaseTryAgain: "请稍后重试。",
    today: "今日",
    tossed: "已丢弃",
    useToday: "今天食用",
    unknown: "未知",
    waitingConfirmation: "待确认",
    weightManagement: "体重管理",
    editProfileSection: "编辑资料栏目",
    editProfile: "编辑资料",
    expiring: "临期",
    profileGoalTitle: "目标",
    profileGoalHint: "让推荐方向保持实用。",
    profileGoalPlaceholder: "在水果失去新鲜度前吃完",
    profileDietTitle: "饮食偏好",
    profileDietHint: "用于日常饮食建议的简短偏好。",
    profileDietPlaceholder: "清淡、低糖、优先吃水果",
    profileCookingTitle: "处理条件",
    profileCookingHint: "你在家可以如何处理食物。",
    profileCookingPlaceholder: "没有烤箱，只做简单清洗和切分",
    profileAvoidTitle: "避免食物",
    profileAvoidHint: "当前仅支持 MVP 范围内的水果。",
    profileAvoidLabel: "要避免的水果",
    profileAllergiesTitle: "过敏源",
    profileAllergiesHint: "用于饮食建议的可选备注。",
    profileHealthNotesTitle: "健康备注",
    profileHealthNotesHint: "让推荐保持稳妥的可选限制。",
    profileOptionalPlaceholder: "可选",
    saveProfile: "保存资料",
    saving: "保存中",
    referenceDateToday: "今天到参考期限",
    checkTiming: "检查保存时间",
    daysLeft: "天剩余",
    daysUnit: "天",
    dayLeft: "天剩余",
    seen: "识别于",
    total: "总数",
  },
} as const satisfies Record<Language, Record<string, string>>;

export type TranslationKey = keyof (typeof translations)["en"];

const foodNames: Record<Language, Record<SupportedFoodLabel, string>> = {
  en: {
    apple: "Apple",
    banana: "Banana",
    litchi: "Litchi",
    pear: "Pear",
  },
  zh: {
    apple: "苹果",
    banana: "香蕉",
    litchi: "荔枝",
    pear: "梨",
  },
};

type LanguageContextValue = {
  language: Language;
  toggleLanguage: () => void;
  t: (key: TranslationKey) => string;
  foodName: (food: SupportedFoodLabel, fallback?: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({
  children,
  initialLanguage = "zh",
}: {
  children: ReactNode;
  initialLanguage?: Language;
}) {
  const [language, setLanguage] = useState<Language>(initialLanguage);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      toggleLanguage: () => setLanguage((current) => (current === "en" ? "zh" : "en")),
      t: (key) => translations[language][key],
      foodName: (food, fallback) => foodNames[language][food] ?? fallback ?? food,
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return value;
}
