import type {
  AdviceItem,
  InventoryItem,
  Profile,
  ShoppingAdviceResponse,
  TodayAdviceResponse,
} from "../api/types";

const now = "2026-06-04T00:00:00.000Z";

export const previewInventoryItems: InventoryItem[] = [
  {
    id: 1,
    evidence_id: "preview-apple",
    user_id: 1,
    camera_id: null,
    food: { id: 1, model_label: "apple", display_name: "Apple" },
    detected_quantity: 2,
    confirmed_quantity: 2,
    unit: "pcs",
    storage_location: "refrigerate",
    first_seen_at: now,
    last_seen_at: now,
    days_stored: 2,
    safe_days: 6,
    remaining_days: 4,
    storage_state: "fresh",
    eat_priority_rank: 2,
    status: "available",
    source_event_id: null,
    pending_change_type: "none",
    pending_detected_quantity: null,
    message: "Still crisp. Keep chilled.",
  },
  {
    id: 2,
    evidence_id: "preview-banana",
    user_id: 1,
    camera_id: null,
    food: { id: 2, model_label: "banana", display_name: "Banana" },
    detected_quantity: 3,
    confirmed_quantity: 3,
    unit: "pcs",
    storage_location: "pantry",
    first_seen_at: now,
    last_seen_at: now,
    days_stored: 3,
    safe_days: 4,
    remaining_days: 1,
    storage_state: "eat_soon",
    eat_priority_rank: 1,
    status: "available",
    source_event_id: null,
    pending_change_type: "none",
    pending_detected_quantity: null,
    message: "Best for breakfast or a snack today.",
  },
  {
    id: 3,
    evidence_id: "preview-litchi",
    user_id: 1,
    camera_id: null,
    food: { id: 3, model_label: "litchi", display_name: "Litchi" },
    detected_quantity: 8,
    confirmed_quantity: 6,
    unit: "pcs",
    storage_location: "refrigerate",
    first_seen_at: now,
    last_seen_at: now,
    days_stored: 4,
    safe_days: 3,
    remaining_days: null,
    storage_state: "check_required",
    eat_priority_rank: null,
    status: "pending_confirm",
    source_event_id: null,
    pending_change_type: "new_quantity",
    pending_detected_quantity: 8,
    message: "Camera detected a quantity change.",
  },
  {
    id: 4,
    evidence_id: "preview-pear",
    user_id: 1,
    camera_id: null,
    food: { id: 4, model_label: "pear", display_name: "Pear" },
    detected_quantity: 1,
    confirmed_quantity: 1,
    unit: "pc",
    storage_location: "pantry",
    first_seen_at: now,
    last_seen_at: now,
    days_stored: 5,
    safe_days: 5,
    remaining_days: 0,
    storage_state: "check_required",
    eat_priority_rank: null,
    status: "available",
    source_event_id: null,
    pending_change_type: "none",
    pending_detected_quantity: null,
    message: "Check softness before eating.",
  },
];

export const previewTodayAdvice: TodayAdviceResponse = {
  today_priority: [
    {
      food: "banana",
      display_name: "Banana",
      storage_state: "eat_soon",
      days_stored: 3,
      safe_days: 4,
      remaining_days: 1,
      eat_priority_rank: 1,
      basis: ["Banana has the shortest remaining freshness window."],
      evidence_ids: ["preview-banana"],
    },
    {
      food: "apple",
      display_name: "Apple",
      storage_state: "fresh",
      days_stored: 2,
      safe_days: 6,
      remaining_days: 4,
      eat_priority_rank: 2,
      basis: ["Apple is stable but already confirmed in inventory."],
      evidence_ids: ["preview-apple"],
    },
  ],
  check_required: [
    {
      food: "litchi",
      display_name: "Litchi",
      storage_state: "check_required",
      days_stored: 4,
      safe_days: 3,
      remaining_days: null,
      eat_priority_rank: null,
      basis: ["Litchi needs a quantity confirmation."],
      evidence_ids: ["preview-litchi"],
    },
    {
      food: "pear",
      display_name: "Pear",
      storage_state: "check_required",
      days_stored: 5,
      safe_days: 5,
      remaining_days: 0,
      eat_priority_rank: null,
      basis: ["Pear should be checked before eating."],
      evidence_ids: ["preview-pear"],
    },
  ],
};

const previewAdviceItems: AdviceItem[] = [
  {
    title: "Eat banana before buying more",
    content: "You already have three bananas and one should be used today.",
    action_type: "avoid_duplicate_purchase",
    related_foods: ["banana"],
    basis: ["Banana has one day remaining."],
    evidence_ids: ["preview-banana"],
    confidence: "high",
  },
  {
    title: "Check litchi before planning dessert",
    content: "Confirm the latest quantity and freshness before adding more fruit.",
    action_type: "check_food",
    related_foods: ["litchi"],
    basis: ["Litchi has a pending quantity change."],
    evidence_ids: ["preview-litchi"],
    confidence: "medium",
  },
];

export const previewShoppingAdvice: ShoppingAdviceResponse = {
  recommendations: previewAdviceItems,
};

export const previewProfile: Profile = {
  id: 1,
  goal: "Eat fruit while it is still fresh.",
  diet_preference: "Light meals, low sugar, fruit first.",
  cooking_condition: "Simple washing, slicing, and chilled storage.",
  avoid_foods: [],
  allergies_optional: "",
  health_notes_optional: "",
  created_at: now,
  updated_at: now,
};
